# Generated by Django 5.2.4 on 2026-04-30 11:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billingprofile_token_usage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.CharField(default='general', max_length=50)),
                ('model_preference', models.CharField(blank=True, default='gemini-flashlite', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('is_editable', models.BooleanField(default=True)),
                ('is_auto_selected', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('normal', 'Normal'), ('custom_agent', 'Custom Agent'), ('domain_agent', 'Domain Agent')], default='normal', max_length=30)),
                ('title', models.CharField(blank=True, default='New Chat', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('message_type', models.CharField(choices=[('normal', 'Normal'), ('live_update', 'Live Update'), ('error', 'Error'), ('draft', 'Draft'), ('title', 'Title')], default='normal', max_length=30)),
                ('content_text', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('sequence_no', models.PositiveIntegerField()),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_no', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('gmail_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('sent', 'Sent'), ('failed', 'Failed')], default='drafted', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='accounts.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='accounts.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='accounts.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('generated_image', 'Generated Image'), ('uploaded_pdf', 'Uploaded PDF')], max_length=30)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='chat_assets/%Y/%m/%d')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('source_url', models.TextField(blank=True, default='')),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_assets', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence_no'), name='unique_message_sequence_per_conversation'),
        ),
    ]
